/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package kasir;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Component;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JPanel;

/**
 *
 * @author LENOVO
 */
public class struk extends javax.swing.JDialog {

    /**
     * Creates new form struk1
     */
    public struk(java.awt.Frame parent, boolean modal, 
              String customer, String tanggal, DefaultTableModel model, 
             String total, String bayar, String kembali) {
        super(parent, modal);
        initComponents();
        
        panelItem.removeAll();
        panelItem.setLayout(new BoxLayout(panelItem, BoxLayout.PAGE_AXIS));
        panelItem.setPreferredSize(null);
        panelItem.setMaximumSize(null);
        panelItem.setMinimumSize(null);

        lHeader.setText("Kopi'ah Ireng");
        lTanggal.setText("Waktu :");
        lTanggalValue.setText(tanggal);

        lCostumer.setText("Pelanggan :");
        lCostumerValue.setText(customer);

        panelItem.removeAll();

        int baris = model.getRowCount();

    for (int i = 0; i < baris; i++) {
        String nama = model.getValueAt(i, 0).toString();
        int harga = parseRupiah(model.getValueAt(i, 1).toString());
        int qty = Integer.parseInt(model.getValueAt(i, 2).toString());
        int subtotal = harga * qty;

        // Baris 1: Nama menu
        JLabel labelNama = new JLabel(nama);
        labelNama.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        labelNama.setAlignmentX(Component.LEFT_ALIGNMENT);
        panelItem.add(labelNama);

        // Baris 2: harga x qty (kiri) dan subtotal (kanan)
        JPanel barisDetail = new JPanel(new java.awt.BorderLayout());
        barisDetail.setBackground(java.awt.Color.WHITE);
        barisDetail.setAlignmentX(Component.LEFT_ALIGNMENT);

        JLabel labelKiri = new JLabel(formatRupiah(harga) + " x " + qty);
        JLabel labelKanan = new JLabel(formatRupiah(subtotal));
        labelKanan.setHorizontalAlignment(SwingConstants.RIGHT);

        labelKiri.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        labelKanan.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));

        barisDetail.add(labelKiri, java.awt.BorderLayout.WEST);
        barisDetail.add(labelKanan, java.awt.BorderLayout.EAST);

        panelItem.add(barisDetail);
        panelItem.add(Box.createVerticalStrut(5));
    }
        panelItem.revalidate();
        panelItem.repaint();
        
    
            lTotal.setText("Total   :");
            lTotalValue.setText(formatRupiah(parseRupiah(total)));
            lBayar.setText("Bayar   :");
            lBayarValue.setText(formatRupiah(parseRupiah(bayar)));
            lKembali.setText("Kembali :");
            lKembaliValue.setText(formatRupiah(parseRupiah(kembali)));
    }
    private String formatRupiah(int angka) {
        Locale indonesia = new Locale("id", "ID");
        NumberFormat format = NumberFormat.getCurrencyInstance(indonesia);
        String hasil = format.format(angka);

        // Hapus "Rp" dan ",00"
        hasil = hasil.replace("Rp", "").replace(",00", "").trim();

        return hasil;
    }

    private struk(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lHeader = new javax.swing.JLabel();
        lTanggal = new javax.swing.JLabel();
        lCostumer = new javax.swing.JLabel();
        lPemisah4 = new javax.swing.JLabel();
        lTotal = new javax.swing.JLabel();
        lBayar = new javax.swing.JLabel();
        lKembali = new javax.swing.JLabel();
        lPemiash1 = new javax.swing.JLabel();
        lPemiash2 = new javax.swing.JLabel();
        lNamaMenuQtyHarga = new javax.swing.JLabel();
        lPemisah3 = new javax.swing.JLabel();
        lPemisah6 = new javax.swing.JLabel();
        tAlamat = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lTanggalValue = new javax.swing.JLabel();
        lCostumerValue = new javax.swing.JLabel();
        lTotalValue = new javax.swing.JLabel();
        lBayarValue = new javax.swing.JLabel();
        lKembaliValue = new javax.swing.JLabel();
        panelItem = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnCetak = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(180, 200));

        lHeader.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lHeader.setText("Kopi'ah Ireng");

        lTanggal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lTanggal.setText("Tanggal");

        lCostumer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lCostumer.setText("Customer");

        lPemisah4.setText("----------------------------------------");

        lTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lTotal.setText("total bayar");

        lBayar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lBayar.setText("bayar");

        lKembali.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lKembali.setText("Kembali");

        lPemiash1.setText("----------------------------------------");

        lPemiash2.setText("----------------------------------------");

        lNamaMenuQtyHarga.setText("Nama menu                       SubTotal");

        lPemisah3.setText("----------------------------------------");

        lPemisah6.setText("----------------------------------------");

        tAlamat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tAlamat.setText("Jl. Ahmad Yani, Nganjuk");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TERIMA KASIH");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tlp: 0858521897398");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ig : kopi'ah ireng");

        lTanggalValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lTanggalValue.setText("20-07-2025 20.19");

        lCostumerValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lCostumerValue.setText("Ntahlah");

        lTotalValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lTotalValue.setText("2.000");

        lBayarValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lBayarValue.setText("5.000");

        lKembaliValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lKembaliValue.setText("3.000");

        panelItem.setBackground(new java.awt.Color(255, 255, 255));
        panelItem.setPreferredSize(new java.awt.Dimension(187, 100));
        panelItem.setVerifyInputWhenFocusTarget(false);
        panelItem.setLayout(new javax.swing.BoxLayout(panelItem, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kasir/png.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lTotal)
                                .addComponent(lBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lKembali))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lTotalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lKembaliValue, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lBayarValue, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(lPemisah4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelItem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lPemisah6)
                        .addComponent(lPemisah3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lPemiash2)
                        .addComponent(lNamaMenuQtyHarga)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lPemiash1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lTanggalValue))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lCostumer, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lCostumerValue, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lHeader)
                .addGap(0, 0, 0)
                .addComponent(tAlamat)
                .addGap(10, 10, 10)
                .addComponent(lPemiash1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTanggal)
                    .addComponent(lTanggalValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lCostumer)
                    .addComponent(lCostumerValue))
                .addComponent(lPemiash2)
                .addGap(0, 0, 0)
                .addComponent(lNamaMenuQtyHarga)
                .addGap(0, 0, 0)
                .addComponent(lPemisah3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelItem, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(lPemisah4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTotal)
                    .addComponent(lTotalValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lBayar)
                    .addComponent(lBayarValue))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lKembali)
                    .addComponent(lKembaliValue))
                .addComponent(lPemisah6)
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel2)
                .addGap(0, 0, 0))
        );

        panelItem.getAccessibleContext().setAccessibleDescription("");

        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCetak)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKembali)))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCetak)
                    .addComponent(btnKembali))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
    java.awt.print.PrinterJob job = java.awt.print.PrinterJob.getPrinterJob();
    job.setJobName("Cetak Struk");

    job.setPrintable((graphics, pageFormat, pageIndex) -> {
        if (pageIndex > 0) {
            return java.awt.print.Printable.NO_SUCH_PAGE;
        }

        java.awt.Graphics2D g2d = (java.awt.Graphics2D) graphics;
        g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
        jPanel1.printAll(g2d); // cetak isi panel
        return java.awt.print.Printable.PAGE_EXISTS;
    });

    boolean doPrint = job.printDialog(); // menampilkan dialog cetak
    if (doPrint) {
        try {
            job.print(); 
            JOptionPane.showMessageDialog(this, "Transaksi berhasil disimpan!");
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Gagal mencetak: " + ex.getMessage());
        }
    }

    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        dispose();
        JOptionPane.showMessageDialog(this, "Transaksi berhasil disimpan!");
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                struk dialog = new struk(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lBayar;
    private javax.swing.JLabel lBayarValue;
    private javax.swing.JLabel lCostumer;
    private javax.swing.JLabel lCostumerValue;
    private javax.swing.JLabel lHeader;
    private javax.swing.JLabel lKembali;
    private javax.swing.JLabel lKembaliValue;
    private javax.swing.JLabel lNamaMenuQtyHarga;
    private javax.swing.JLabel lPemiash1;
    private javax.swing.JLabel lPemiash2;
    private javax.swing.JLabel lPemisah3;
    private javax.swing.JLabel lPemisah4;
    private javax.swing.JLabel lPemisah6;
    private javax.swing.JLabel lTanggal;
    private javax.swing.JLabel lTanggalValue;
    private javax.swing.JLabel lTotal;
    private javax.swing.JLabel lTotalValue;
    private javax.swing.JPanel panelItem;
    private javax.swing.JLabel tAlamat;
    // End of variables declaration//GEN-END:variables
    public int parseRupiah(String text) {
        if (text == null || text.trim().isEmpty()) return 0;
        return Integer.parseInt(text.replaceAll("[^\\d]", ""));
    }

}
